language: c

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - lcov
      - valgrind
      - libgtest-dev
      - clang
      - clang-tidy
      - python3-pip
      - cppcheck

install:
  - pip3 install --user cpplint

before_script:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  - travis_retry wget --no-check-certificate https://github.com/Kitware/CMake/releases/download/v3.22.0-rc2/cmake-3.22.0-rc2-linux-x86_64.tar.gz
  - tar -xvf cmake-3.22.0-rc2-linux-x86_64.tar.gz > /dev/null
  - mv cmake-3.22.0-rc2-linux-x86_64 cmake-install
  - PATH=${DEPS_DIR}/cmake-install:${DEPS_DIR}/cmake-install/bin:$PATH
  - cd ${TRAVIS_BUILD_DIR}
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd ${TRAVIS_BUILD_DIR}

jobs:
  include:
    - name: "Building"
      script:
        - mkdir build
        - cd build
        - scan-build cmake ..
        - scan-build make
    - name: "Unit tests"
      script:
        - mkdir unit_tests
        - cd unit_tests
        - cmake ..
        - make
        - cd tests/unit/file_reader
        - ./file_reader_test
        - cd ../searcher
        - ./searcher_test
        - cd ../file_word_searcher
        - ./file_word_searcher_sync_test
        - ./file_word_searcher_async_test
        - lcov -t "file_word_searcher_async_test" -o coverage.txt -c -d ./
        - lcov -t "file_word_searcher_sync_test" -o coverage.txt -c -d ./
        - bash <(curl -s https://codecov.io/bash)
    - name: "Valgrind"
      script:
        - mkdir valgrind
        - cd valgrind
        - cmake ..
        - make
        - cd tests/unit/file_word_searcher
        - valgrind --tool=memcheck --leak-check=full ./file_word_searcher_sync_test
        - valgrind --tool=memcheck --leak-check=full ./file_word_searcher_async_test
    - name: "CPPLint & CPPCheck"
      script:
        - cpplint --extensions=c,h --filter=-runtime/references,-legal/copyright,-build/include_subdir,-whitespace/line_length,-readability/casting src/file_reader/* src/file_word_searcher/sync/* src/file_word_searcher/async/* src/searcher/* cmd/*
        - cppcheck -q --enable=all -I src/file_word_searcher -I src/file_reader -I src/searcher --suppress=missingIncludeSystem ./cmd
    - name: "Stress test"
      script:
        - bash stress_tests.sh
    - name: "Sanitizer address"
      script:
        - mkdir build
        - cd build
        - cmake -Daddress=ON -Dparallel=OFF ..
        - make
        - cmake -Daddress=ON -Dparallel=ON ..
        - make
    - name: "Sanitizer memory"
      script:
        - mkdir build
        - cd build
        - cmake -Dmemory=ON -Dparallel=OFF ..
        - make
        - cmake -Dmemory=ON -Dparallel=ON ..
        - make
    - name: "Sanitizer undefined"
      script:
        - mkdir build
        - cd build
        - cmake -Dundefined=ON -Dparallel=OFF ..
        - make
        - cmake -Dundefined=ON -Dparallel=ON ..
        - make
    - name: "Sanitizer thread"
      script:
        - mkdir build
        - cd build
        - cmake -Dthread=ON -Dparallel=OFF ..
        - make
        - cmake -Dthread=ON -Dparallel=ON ..
        - make