language: c

compiler:
 - gcc

install:
 - sudo apt-get update
 - sudo apt-get install -y valgrind
 - sudo apt-get install cmake -y
 - sudo apt-get install libgtest-dev -y
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib
 - cd /home/travis/build/nezhibitskiy/advanced_c_cpp

script:
 - ./linters/run.sh
 - mkdir build
 - cd build
 - cmake ..
 - make
 - ./hw_test
 - valgrind --tool=memcheck --leak-check=full ./hw_test