language: c

compiler:
 - gcc

addons:
 apt:
  update: true
  packages:
   - cmake
   - lcov
   - valgrind
   - libgtest-dev
   - clang

install: skip

before_script:
 - cd /usr/src/gtest
 - sudo cmake CMakeLists.txt
 - sudo make
 - sudo cp *.a /usr/lib
 - cd /home/travis/build/nezhibitskiy/advanced_c_cpp

jobs:
 include:
  - name: "Linters"
    script: ./linters/run.sh
  - name: "Building"
    script:
     - mkdir build
     - cd build
     - cmake ..
     - make
  - name: "Tests"
    script:
     - mkdir tests
     - cd tests
     - cmake ..
     - make
     - ./hw_test
  - name: "Coverage"
    script:
     - mkdir coverage
     - cd coverage
     - cmake ..
     - make
     - ./hw_test
     - lcov -t "hw_test" -o coverage.txt -c -d ./
     - bash <(curl -s https://codecov.io/bash)
  - name: "Valgrind"
    script:
     - mkdir valgrind
     - cd valgrind
     - cmake ..
     - make
     - ./hw_test
     - valgrind --tool=memcheck --leak-check=full ./hw_test