language: c

compiler:
  - gcc

addons:
  apt:
    update: true
    packages:
      - cmake
      - lcov
      - valgrind
      - libgtest-dev
      - clang
    sources:
      - kalakris-cmake

install: skip

before_script:
  - cd /usr/src/gtest
  - sudo cmake CMakeLists.txt
  - sudo make
  - sudo cp *.a /usr/lib
  - cd /home/travis/build/nezhibitskiy/advanced_c_cpp

jobs:
  include:
    - name: "Building"
      script:
        - mkdir build
        - cd build
        - cmake ..
        - make
    - name: "Unit tests"
      script:
        - mkdir unit_tests
        - cd unit_tests
        - cmake ..
        - make
        - cd tests/unit/file_reader
        - ./file_reader_test
        - cd ../searcher
        - ./searcher_test
        - cd ../file_word_searcher
        - ./file_word_searcher_sync_test
        - ./file_word_searcher_async_test
    - name: "Valgrind"
      script:
        - mkdir valgrind
        - cd valgrind
        - cmake ..
        - make
        - cd tests/unit/file_word_searcher
        - valgrind --tool=memcheck --leak-check=full ./file_word_searcher_sync_test
        - valgrind --tool=memcheck --leak-check=full ./file_word_searcher_async_test
    - name: "Stress test"
      script:
        - bash stress_tests.sh
    - name: "Sanitizer address"
      script:
        - mkdir build
        - cd build
        - cmake -Daddress=ON -Dparallel=OFF ..
        - make
        - cmake -Daddress=ON -Dparallel=ON ..
        - make
    - name: "Sanitizer memory"
      script:
        - mkdir build
        - cd build
        - cmake -Dmemory=ON -Dparallel=OFF ..
        - make
        - cmake -Dmemory=ON -Dparallel=ON ..
        - make
    - name: "Sanitizer undefined"
      script:
        - mkdir build
        - cd build
        - cmake -Dundefined=ON -Dparallel=OFF ..
        - make
        - cmake -Dundefined=ON -Dparallel=ON ..
        - make
    - name: "Sanitizer thread"
      script:
        - mkdir build
        - cd build
        - cmake -Dthread=ON -Dparallel=OFF ..
        - make
        - cmake -Dthread=ON -Dparallel=ON ..
        - make